import { Parcel, ResidentProfile, AuthUser, ActivityLogItem, SmsLogItem, HubSettings } from "@/types";

export const SEED_USERS: AuthUser[] = [
  {
    id: "usr-resident-1",
    email: "juan.delacruz@example.com",
    name: "Juan Dela Cruz",
    phone: "0917 123 4567",
    role: "resident",
    unit: "Unit 101",
    tower: "Tower A",
    plan: "PREMIUM",
    planStatus: "ACTIVE",
    paymentMethod: "GCASH",
    paymentReference: "GC-9821-4402",
    residentCode: "CK-000123",
    createdAt: "2026-08-01T08:00:00Z",
  },
  {
    id: "usr-resident-2",
    email: "maria.santos@example.com",
    name: "Maria Santos",
    phone: "0918 234 5678",
    role: "resident",
    unit: "Unit 304",
    tower: "Tower B",
    plan: "REGULAR",
    planStatus: "ACTIVE",
    paymentMethod: "GCASH",
    paymentReference: "GC-1029-3381",
    residentCode: "CK-000189",
    createdAt: "2026-08-15T09:30:00Z",
  },
  {
    id: "usr-admin-1",
    email: "admin@ckcondohub.com",
    name: "Station 1 Front Desk Staff",
    phone: "0917 999 8888",
    role: "admin",
    createdAt: "2026-07-01T08:00:00Z",
  },
];

export const SEED_RESIDENTS: ResidentProfile[] = [
  {
    id: "usr-resident-1",
    name: "Juan Dela Cruz",
    email: "juan.delacruz@example.com",
    phone: "0917 123 4567",
    unit: "Unit 101",
    tower: "Tower A",
    building: "CK Buildersville Condominium",
    plan: "PREMIUM",
    planStatus: "ACTIVE",
    paymentMethod: "GCASH",
    paymentReference: "GC-9821-4402",
    residentCode: "CK-000123",
    authorizedClaimant: "Maria Dela Cruz (Spouse)",
    claimantPhone: "0918 987 6543",
    notifications: {
      smsArrival: true,
      smsReminder: true,
      emailDigest: false,
      promoUpdates: false,
    },
    deliveryCreditsLeft: 2,
    totalParcelsReceived: 18,
    activeParcelsCount: 3,
    status: "ACTIVE",
    createdAt: "2026-08-01T08:00:00Z",
  },
  {
    id: "usr-resident-2",
    name: "Maria Santos",
    email: "maria.santos@example.com",
    phone: "0918 234 5678",
    unit: "Unit 304",
    tower: "Tower B",
    building: "CK Buildersville Condominium",
    plan: "REGULAR",
    planStatus: "ACTIVE",
    paymentMethod: "GCASH",
    paymentReference: "GC-1029-3381",
    residentCode: "CK-000189",
    authorizedClaimant: "Carlo Santos (Son)",
    claimantPhone: "0919 111 2222",
    notifications: {
      smsArrival: true,
      smsReminder: true,
      emailDigest: true,
      promoUpdates: true,
    },
    deliveryCreditsLeft: 0,
    totalParcelsReceived: 9,
    activeParcelsCount: 1,
    status: "ACTIVE",
    createdAt: "2026-08-15T09:30:00Z",
  },
  {
    id: "usr-resident-3",
    name: "Robert Lim",
    email: "robert.lim@example.com",
    phone: "0920 345 6789",
    unit: "Unit 512",
    tower: "Tower A",
    building: "CK Buildersville Condominium",
    plan: "PER_PARCEL",
    planStatus: "ACTIVE",
    paymentMethod: "CASH_COUNTER",
    residentCode: "CK-000215",
    notifications: {
      smsArrival: true,
      smsReminder: false,
      emailDigest: false,
      promoUpdates: false,
    },
    totalParcelsReceived: 4,
    activeParcelsCount: 1,
    status: "ACTIVE",
    createdAt: "2026-09-01T14:20:00Z",
  },
];

export const SEED_PARCELS: Parcel[] = [
  {
    id: "pcl-101",
    trackingNumber: "SPX-PH-2026-8921",
    courier: "SPX Express",
    courierColor: "#EE4D2D",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Shelf A-04",
    size: "Small",
    dateArrived: "Sept 18, 2026 • 10:45 AM",
    deadline: "Sept 21, 2026",
    holdingFee: "₱0.00 (Free)",
    status: "READY",
    claimCode: "CK-8921",
    notes: "Fragile sticker attached",
  },
  {
    id: "pcl-102",
    trackingNumber: "JT-PH-9920148",
    courier: "J&T Express",
    courierColor: "#D21F1F",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Shelf B-12",
    size: "Medium",
    dateArrived: "Sept 19, 2026 • 02:15 PM",
    deadline: "Sept 22, 2026",
    holdingFee: "₱0.00 (Free)",
    status: "READY",
    claimCode: "CK-0148",
  },
  {
    id: "pcl-103",
    trackingNumber: "FL-2026-58190",
    courier: "Flash Express",
    courierColor: "#FFB800",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Shelf C-01",
    size: "Large",
    dateArrived: "Sept 16, 2026 • 11:30 AM",
    deadline: "Sept 19, 2026 (Overdue)",
    holdingFee: "₱10.00 (1 Day)",
    status: "OVERDUE",
    claimCode: "CK-8190",
  },
  {
    id: "pcl-104",
    trackingNumber: "LBC-2026-33901",
    courier: "LBC Express",
    courierColor: "#E31837",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Shelf B-02",
    size: "Small",
    dateArrived: "Sept 20, 2026 • 09:15 AM",
    deadline: "Sept 23, 2026",
    holdingFee: "₱0.00 (Free)",
    status: "READY",
    claimCode: "CK-3901",
  },
  {
    id: "pcl-105",
    trackingNumber: "SPX-PH-2026-7734",
    courier: "SPX Express",
    courierColor: "#EE4D2D",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Sept 13, 2026 • 09:00 AM",
    deadline: "Sept 16, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-7734",
    claimedAt: "Sept 15, 2026 • 05:20 PM",
    claimedBy: "Juan Dela Cruz (Self)",
  },
  {
    id: "pcl-106",
    trackingNumber: "JT-PH-8819231",
    courier: "J&T Express",
    courierColor: "#D21F1F",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Archived",
    size: "Medium",
    dateArrived: "Sept 16, 2026 • 11:15 AM",
    deadline: "Sept 19, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-9231",
    claimedAt: "Sept 18, 2026 • 04:30 PM",
    claimedBy: "Maria Santos (Self)",
  },
  {
    id: "pcl-107",
    trackingNumber: "FL-2026-90214",
    courier: "Flash Express",
    courierColor: "#FFB800",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Sept 10, 2026 • 02:00 PM",
    deadline: "Sept 13, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-0214",
    claimedAt: "Sept 12, 2026 • 06:15 PM",
    claimedBy: "Carlo Santos (Son)",
  },
  {
    id: "pcl-108",
    trackingNumber: "2GO-MNL-48192",
    courier: "2GO Express",
    courierColor: "#0066B2",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Archived",
    size: "Large",
    dateArrived: "Sept 03, 2026 • 09:30 AM",
    deadline: "Sept 06, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-8192",
    claimedAt: "Sept 05, 2026 • 11:20 AM",
    claimedBy: "Maria Santos (Self)",
  },
  {
    id: "pcl-109",
    trackingNumber: "JT-PH-4491023",
    courier: "J&T Express",
    courierColor: "#D21F1F",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Archived",
    size: "Medium",
    dateArrived: "Sept 08, 2026 • 01:20 PM",
    deadline: "Sept 11, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-1023",
    claimedAt: "Sept 10, 2026 • 02:40 PM",
    claimedBy: "Maria Dela Cruz (Spouse)",
  },
];

export const SEED_ACTIVITY_LOGS: ActivityLogItem[] = [
  {
    id: "act-1",
    type: "PARCEL_INGESTED",
    title: "Parcel Received: SPX-PH-2026-8921",
    description: "Ingested from SPX Express for Juan Dela Cruz (Unit 101). Stored at Shelf A-04.",
    timestamp: "Sept 18, 2026 • 10:45 AM",
    actor: "Station 1 Front Desk Staff",
    trackingNumber: "SPX-PH-2026-8921",
    badgeColor: "bg-orange-500",
  },
  {
    id: "act-2",
    type: "SMS_DISPATCHED",
    title: "SMS Alert Dispatched to Unit 101",
    description: "Sent arrival notification with claim code CK-8921 to 0917 123 4567.",
    timestamp: "Sept 18, 2026 • 10:46 AM",
    actor: "Automated Gateway",
    trackingNumber: "SPX-PH-2026-8921",
    badgeColor: "bg-blue-500",
  },
  {
    id: "act-3",
    type: "PARCEL_INGESTED",
    title: "Parcel Received: JT-PH-9920148",
    description: "Ingested from J&T Express for Juan Dela Cruz (Unit 101). Stored at Shelf B-12.",
    timestamp: "Sept 19, 2026 • 02:15 PM",
    actor: "Station 1 Front Desk Staff",
    trackingNumber: "JT-PH-9920148",
    badgeColor: "bg-red-500",
  },
  {
    id: "act-4",
    type: "PARCEL_INGESTED",
    title: "Parcel Received: LBC-2026-33901",
    description: "Ingested from LBC Express for Maria Santos (Unit 304). Stored at Shelf B-02.",
    timestamp: "Sept 20, 2026 • 09:15 AM",
    actor: "Station 1 Front Desk Staff",
    trackingNumber: "LBC-2026-33901",
    badgeColor: "bg-rose-500",
  },
  {
    id: "act-5",
    type: "PARCEL_RELEASED",
    title: "Parcel Released: SPX-PH-2026-7734",
    description: "Verified passcode CK-7734 and handed package to Juan Dela Cruz (Self).",
    timestamp: "Sept 15, 2026 • 05:20 PM",
    actor: "Station 1 Front Desk Staff",
    trackingNumber: "SPX-PH-2026-7734",
    badgeColor: "bg-green-600",
  },
];

export const SEED_SMS_LOGS: SmsLogItem[] = [
  {
    id: "sms-1",
    recipientPhone: "0917 123 4567",
    recipientName: "Juan Dela Cruz",
    messageText: "CK Condo Drop Hub: Package SPX-PH-2026-8921 from SPX Express has arrived at Shelf A-04. Your claim passcode is CK-8921. Free holding until Sept 21, 2026.",
    status: "DELIVERED",
    timestamp: "Sept 18, 2026 • 10:46 AM",
    trackingNumber: "SPX-PH-2026-8921",
    costEstimate: "₱0.40",
  },
  {
    id: "sms-2",
    recipientPhone: "0917 123 4567",
    recipientName: "Juan Dela Cruz",
    messageText: "CK Condo Drop Hub: Package JT-PH-9920148 from J&T Express has arrived at Shelf B-12. Your claim passcode is CK-0148. Free holding until Sept 22, 2026.",
    status: "DELIVERED",
    timestamp: "Sept 19, 2026 • 02:16 PM",
    trackingNumber: "JT-PH-9920148",
    costEstimate: "₱0.40",
  },
  {
    id: "sms-3",
    recipientPhone: "0918 234 5678",
    recipientName: "Maria Santos",
    messageText: "CK Condo Drop Hub: Package LBC-2026-33901 from LBC Express has arrived at Shelf B-02. Your claim passcode is CK-3901. Free holding until Sept 23, 2026.",
    status: "DELIVERED",
    timestamp: "Sept 20, 2026 • 09:16 AM",
    trackingNumber: "LBC-2026-33901",
    costEstimate: "₱0.40",
  },
];

export const DEFAULT_HUB_SETTINGS: HubSettings = {
  hubName: "CK Condo Drop Hub",
  buildingName: "CK Buildersville Condominium",
  stationName: "Station 1 Front Desk",
  freeDaysRegular: 3,
  freeDaysPremium: 7,
  overdueFeePerDay: 10,
  smsSenderId: "CKCONDO",
  autoPrintIntakeLabel: true,
  soundEnabled: true,
  maxShelfSlots: 60,
};
