import { Parcel, ResidentProfile, AuthUser, ActivityLogItem, SmsLogItem, HubSettings, DeskInquiry } from "@/types";

export const SEED_USERS: AuthUser[] = [
  {
    id: "usr-resident-1",
    email: "juan.delacruz@example.com",
    name: "Juan Dela Cruz",
    phone: "0917 123 4567",
    role: "resident",
    unit: "Unit 101",
    tower: "Tower A",
    plan: "PREMIUM",
    planStatus: "ACTIVE",
    paymentMethod: "GCASH",
    paymentReference: "GC-9821-4402",
    residentCode: "CK-000123",
    deliveryCreditsLeft: 2,
    subscriptionExpiry: "2026-10-01T23:59:59Z",
    createdAt: "2026-08-01T08:00:00Z",
  },
  {
    id: "usr-resident-2",
    email: "maria.santos@example.com",
    name: "Maria Santos",
    phone: "0918 234 5678",
    role: "resident",
    unit: "Unit 304",
    tower: "Tower B",
    plan: "REGULAR",
    planStatus: "ACTIVE",
    paymentMethod: "GCASH",
    paymentReference: "GC-1029-3381",
    residentCode: "CK-000189",
    deliveryCreditsLeft: 0,
    subscriptionExpiry: "2026-10-15T23:59:59Z",
    createdAt: "2026-08-15T09:30:00Z",
  },
  {
    id: "usr-admin-1",
    email: "admin@ckcondohub.com",
    name: "Lobby Staff Admin",
    phone: "0917 999 8888",
    role: "admin",
    createdAt: "2026-07-01T08:00:00Z",
  },
];

export const SEED_RESIDENTS: ResidentProfile[] = [
  {
    id: "usr-resident-1",
    name: "Juan Dela Cruz",
    email: "juan.delacruz@example.com",
    phone: "0917 123 4567",
    unit: "Unit 101",
    tower: "Tower A",
    building: "CK Buildersville Condominium",
    plan: "PREMIUM",
    planStatus: "ACTIVE",
    paymentMethod: "GCASH",
    paymentReference: "GC-9821-4402",
    residentCode: "CK-000123",
    authorizedClaimant: "Maria Dela Cruz (Spouse)",
    claimantPhone: "0918 987 6543",
    notifications: {
      smsArrival: true,
      smsReminder: true,
      emailDigest: false,
      promoUpdates: false,
    },
    deliveryCreditsLeft: 2,
    subscriptionExpiry: "2026-10-01T23:59:59Z",
    totalParcelsReceived: 18,
    activeParcelsCount: 3,
    status: "ACTIVE",
    createdAt: "2026-08-01T08:00:00Z",
  },
  {
    id: "usr-resident-2",
    name: "Maria Santos",
    email: "maria.santos@example.com",
    phone: "0918 234 5678",
    unit: "Unit 304",
    tower: "Tower B",
    building: "CK Buildersville Condominium",
    plan: "REGULAR",
    planStatus: "ACTIVE",
    paymentMethod: "GCASH",
    paymentReference: "GC-1029-3381",
    residentCode: "CK-000189",
    authorizedClaimant: "Carlo Santos (Son)",
    claimantPhone: "0919 111 2222",
    notifications: {
      smsArrival: true,
      smsReminder: true,
      emailDigest: true,
      promoUpdates: true,
    },
    deliveryCreditsLeft: 0,
    subscriptionExpiry: "2026-10-15T23:59:59Z",
    totalParcelsReceived: 9,
    activeParcelsCount: 1,
    status: "ACTIVE",
    createdAt: "2026-08-15T09:30:00Z",
  },
  {
    id: "usr-resident-3",
    name: "Robert Lim",
    email: "robert.lim@example.com",
    phone: "0920 345 6789",
    unit: "Unit 512",
    tower: "Tower A",
    building: "CK Buildersville Condominium",
    plan: "PER_PARCEL",
    planStatus: "ACTIVE",
    paymentMethod: "CASH_COUNTER",
    residentCode: "CK-000215",
    notifications: {
      smsArrival: true,
      smsReminder: false,
      emailDigest: false,
      promoUpdates: false,
    },
    totalParcelsReceived: 4,
    activeParcelsCount: 1,
    status: "ACTIVE",
    createdAt: "2026-09-01T14:20:00Z",
  },
];

export const SEED_PARCELS: Parcel[] = [
  {
    id: "pcl-101",
    trackingNumber: "SPX-PH-2026-8921",
    courier: "SPX Express",
    courierColor: "#EE4D2D",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Shelf A-04",
    size: "Small",
    dateArrived: "Sept 18, 2026 • 10:45 AM",
    deadline: "Sept 21, 2026",
    holdingFee: "₱0.00 (Free)",
    status: "READY",
    claimCode: "CK-8921",
    notes: "Fragile sticker attached",
  },
  {
    id: "pcl-102",
    trackingNumber: "JT-PH-9920148",
    courier: "J&T Express",
    courierColor: "#D21F1F",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Shelf B-12",
    size: "Medium",
    dateArrived: "Sept 19, 2026 • 02:15 PM",
    deadline: "Sept 22, 2026",
    holdingFee: "₱0.00 (Free)",
    status: "READY",
    claimCode: "CK-0148",
  },
  {
    id: "pcl-103",
    trackingNumber: "FL-2026-58190",
    courier: "Flash Express",
    courierColor: "#FFB800",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Shelf C-01",
    size: "Large",
    dateArrived: "Sept 16, 2026 • 11:30 AM",
    deadline: "Sept 19, 2026 (Overdue)",
    holdingFee: "₱10.00 (1 Day)",
    status: "OVERDUE",
    claimCode: "CK-8190",
  },
  {
    id: "pcl-104",
    trackingNumber: "LBC-2026-33901",
    courier: "LBC Express",
    courierColor: "#E31837",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Shelf B-02",
    size: "Small",
    dateArrived: "Sept 20, 2026 • 09:15 AM",
    deadline: "Sept 23, 2026",
    holdingFee: "₱0.00 (Free)",
    status: "READY",
    claimCode: "CK-3901",
  },
  {
    id: "pcl-105",
    trackingNumber: "SPX-PH-2026-7734",
    courier: "SPX Express",
    courierColor: "#EE4D2D",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Sept 13, 2026 • 09:00 AM",
    deadline: "Sept 16, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-7734",
    claimedAt: "Sept 15, 2026 • 05:20 PM",
    claimedBy: "Juan Dela Cruz (Self)",
  },
  {
    id: "pcl-106",
    trackingNumber: "JT-PH-8819231",
    courier: "J&T Express",
    courierColor: "#D21F1F",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Archived",
    size: "Medium",
    dateArrived: "Sept 16, 2026 • 11:15 AM",
    deadline: "Sept 19, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-9231",
    claimedAt: "Sept 18, 2026 • 04:30 PM",
    claimedBy: "Maria Santos (Self)",
  },
  {
    id: "pcl-107",
    trackingNumber: "FL-2026-90214",
    courier: "Flash Express",
    courierColor: "#FFB800",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Sept 10, 2026 • 02:00 PM",
    deadline: "Sept 13, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-0214",
    claimedAt: "Sept 12, 2026 • 06:15 PM",
    claimedBy: "Carlo Santos (Son)",
  },
  {
    id: "pcl-108",
    trackingNumber: "2GO-MNL-48192",
    courier: "2GO Express",
    courierColor: "#0066B2",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Archived",
    size: "Large",
    dateArrived: "Sept 03, 2026 • 09:30 AM",
    deadline: "Sept 06, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-8192",
    claimedAt: "Sept 05, 2026 • 11:20 AM",
    claimedBy: "Maria Santos (Self)",
  },
  {
    id: "pcl-109",
    trackingNumber: "JT-PH-4491023",
    courier: "J&T Express",
    courierColor: "#D21F1F",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Archived",
    size: "Medium",
    dateArrived: "Sept 08, 2026 • 01:20 PM",
    deadline: "Sept 11, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-1023",
    claimedAt: "Sept 10, 2026 • 02:40 PM",
    claimedBy: "Maria Dela Cruz (Spouse)",
  },
  {
    id: "pcl-110",
    trackingNumber: "FL-2026-88301",
    courier: "Flash Express",
    courierColor: "#FFB800",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Shelf C-03",
    size: "Medium",
    dateArrived: "Sept 15, 2026 • 11:30 AM",
    deadline: "Sept 18, 2026",
    holdingFee: "₱20.00 (2 Days)",
    status: "OVERDUE",
    claimCode: "CK-8301",
    notes: "Overdue by 2 days",
  },
  {
    id: "pcl-111",
    trackingNumber: "SPX-PH-2026-9904",
    courier: "SPX Express",
    courierColor: "#EE4D2D",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Sept 01, 2026 • 10:00 AM",
    deadline: "Sept 04, 2026",
    holdingFee: "₱0.00",
    status: "DELIVERED_DOOR",
    claimCode: "CK-9904",
    claimedAt: "Sept 02, 2026 • 07:15 PM",
    claimedBy: "Staff Admin Door Delivery",
    notes: "Delivered to Unit 304 door",
  },
  {
    id: "pcl-112",
    trackingNumber: "LBC-2026-91024",
    courier: "LBC Express",
    courierColor: "#E31837",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Aug 28, 2026 • 02:10 PM",
    deadline: "Aug 31, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-1024",
    claimedAt: "Aug 30, 2026 • 04:15 PM",
    claimedBy: "Juan Dela Cruz (Self)",
  },
  {
    id: "pcl-113",
    trackingNumber: "FL-2026-44019",
    courier: "Flash Express",
    courierColor: "#FFB800",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Archived",
    size: "Medium",
    dateArrived: "Aug 20, 2026 • 11:00 AM",
    deadline: "Aug 23, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-4019",
    claimedAt: "Aug 21, 2026 • 06:45 PM",
    claimedBy: "Juan Dela Cruz (Self)",
  },
  {
    id: "pcl-114",
    trackingNumber: "2GO-MNL-33109",
    courier: "2GO Express",
    courierColor: "#0066B2",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Archived",
    size: "Large",
    dateArrived: "Aug 15, 2026 • 03:40 PM",
    deadline: "Aug 18, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-3109",
    claimedAt: "Aug 16, 2026 • 01:25 PM",
    claimedBy: "Maria Dela Cruz (Spouse)",
  },
  {
    id: "pcl-115",
    trackingNumber: "SPX-PH-2026-6612",
    courier: "SPX Express",
    courierColor: "#EE4D2D",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Aug 05, 2026 • 09:30 AM",
    deadline: "Aug 08, 2026",
    holdingFee: "₱0.00",
    status: "DELIVERED_DOOR",
    claimCode: "CK-6612",
    claimedAt: "Aug 06, 2026 • 07:00 PM",
    claimedBy: "Staff Admin Door Delivery",
    notes: "Delivered to Unit 101 door",
  },
  {
    id: "pcl-116",
    trackingNumber: "JT-PH-1102983",
    courier: "J&T Express",
    courierColor: "#D21F1F",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Archived",
    size: "Medium",
    dateArrived: "Jul 28, 2026 • 10:15 AM",
    deadline: "Jul 31, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-2983",
    claimedAt: "Jul 29, 2026 • 05:00 PM",
    claimedBy: "Juan Dela Cruz (Self)",
  },
  {
    id: "pcl-117",
    trackingNumber: "LBC-2026-11892",
    courier: "LBC Express",
    courierColor: "#E31837",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Aug 25, 2026 • 01:00 PM",
    deadline: "Aug 28, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-1892",
    claimedAt: "Aug 27, 2026 • 03:30 PM",
    claimedBy: "Maria Santos (Self)",
  },
  {
    id: "pcl-118",
    trackingNumber: "FL-2026-77821",
    courier: "Flash Express",
    courierColor: "#FFB800",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Aug 12, 2026 • 10:45 AM",
    deadline: "Aug 15, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-7821",
    claimedAt: "Aug 14, 2026 • 05:20 PM",
    claimedBy: "Carlo Santos (Son)",
  },
  {
    id: "pcl-119",
    trackingNumber: "JT-PH-5591024",
    courier: "J&T Express",
    courierColor: "#D21F1F",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Archived",
    size: "Medium",
    dateArrived: "Aug 02, 2026 • 02:15 PM",
    deadline: "Aug 05, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-1024",
    claimedAt: "Aug 04, 2026 • 06:10 PM",
    claimedBy: "Maria Santos (Self)",
  },
  {
    id: "pcl-120",
    trackingNumber: "2GO-MNL-19028",
    courier: "2GO Express",
    courierColor: "#0066B2",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Jul 25, 2026 • 09:30 AM",
    deadline: "Jul 28, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-9028",
    claimedAt: "Jul 26, 2026 • 04:45 PM",
    claimedBy: "Maria Santos (Self)",
  },
  {
    id: "pcl-121",
    trackingNumber: "SPX-PH-2026-4410",
    courier: "SPX Express",
    courierColor: "#EE4D2D",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Jul 18, 2026 • 11:15 AM",
    deadline: "Jul 21, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-4410",
    claimedAt: "Jul 19, 2026 • 06:30 PM",
    claimedBy: "Carlo Santos (Son)",
  },
  {
    id: "pcl-122",
    trackingNumber: "FL-2026-33910",
    courier: "Flash Express",
    courierColor: "#FFB800",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Archived",
    size: "Medium",
    dateArrived: "Jul 10, 2026 • 02:00 PM",
    deadline: "Jul 13, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-3910",
    claimedAt: "Jul 12, 2026 • 05:15 PM",
    claimedBy: "Maria Santos (Self)",
  },
  {
    id: "pcl-123",
    trackingNumber: "LBC-2026-88019",
    courier: "LBC Express",
    courierColor: "#E31837",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Jul 01, 2026 • 10:00 AM",
    deadline: "Jul 04, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-8019",
    claimedAt: "Jul 03, 2026 • 03:20 PM",
    claimedBy: "Maria Santos (Self)",
  },
  {
    id: "pcl-124",
    trackingNumber: "LBC-2026-66712",
    courier: "LBC Express",
    courierColor: "#E31837",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Jul 20, 2026 • 01:15 PM",
    deadline: "Jul 23, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-6712",
    claimedAt: "Jul 22, 2026 • 04:30 PM",
    claimedBy: "Juan Dela Cruz (Self)",
  },
  {
    id: "pcl-125",
    trackingNumber: "FL-2026-11902",
    courier: "Flash Express",
    courierColor: "#FFB800",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Archived",
    size: "Medium",
    dateArrived: "Jul 14, 2026 • 10:45 AM",
    deadline: "Jul 17, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-1902",
    claimedAt: "Jul 15, 2026 • 05:40 PM",
    claimedBy: "Maria Dela Cruz (Spouse)",
  },
  {
    id: "pcl-126",
    trackingNumber: "2GO-MNL-88219",
    courier: "2GO Express",
    courierColor: "#0066B2",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Archived",
    size: "Large",
    dateArrived: "Jul 07, 2026 • 03:20 PM",
    deadline: "Jul 10, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-8219",
    claimedAt: "Jul 09, 2026 • 02:15 PM",
    claimedBy: "Juan Dela Cruz (Self)",
  },
  {
    id: "pcl-127",
    trackingNumber: "SPX-PH-2026-1029",
    courier: "SPX Express",
    courierColor: "#EE4D2D",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Jun 30, 2026 • 09:00 AM",
    deadline: "Jul 03, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-1029",
    claimedAt: "Jul 01, 2026 • 06:10 PM",
    claimedBy: "Juan Dela Cruz (Self)",
  },
];

export const SEED_ACTIVITY_LOGS: ActivityLogItem[] = [
  {
    id: "act-1",
    type: "PARCEL_INGESTED",
    title: "Parcel Received: SPX-PH-2026-8921",
    description: "Ingested from SPX Express for Juan Dela Cruz (Unit 101). Stored at Shelf A-04.",
    timestamp: "Sept 18, 2026 • 10:45 AM",
    actor: "Lobby Staff Admin",
    trackingNumber: "SPX-PH-2026-8921",
    badgeColor: "bg-orange-500",
  },
  {
    id: "act-2",
    type: "SMS_DISPATCHED",
    title: "SMS Alert Dispatched to Unit 101",
    description: "Sent arrival notification with claim code CK-8921 to 0917 123 4567.",
    timestamp: "Sept 18, 2026 • 10:46 AM",
    actor: "Automated Gateway",
    trackingNumber: "SPX-PH-2026-8921",
    badgeColor: "bg-blue-500",
  },
  {
    id: "act-3",
    type: "PARCEL_INGESTED",
    title: "Parcel Received: JT-PH-9920148",
    description: "Ingested from J&T Express for Juan Dela Cruz (Unit 101). Stored at Shelf B-12.",
    timestamp: "Sept 19, 2026 • 02:15 PM",
    actor: "Lobby Staff Admin",
    trackingNumber: "JT-PH-9920148",
    badgeColor: "bg-red-500",
  },
  {
    id: "act-4",
    type: "PARCEL_INGESTED",
    title: "Parcel Received: LBC-2026-33901",
    description: "Ingested from LBC Express for Maria Santos (Unit 304). Stored at Shelf B-02.",
    timestamp: "Sept 20, 2026 • 09:15 AM",
    actor: "Lobby Staff Admin",
    trackingNumber: "LBC-2026-33901",
    badgeColor: "bg-rose-500",
  },
  {
    id: "act-5",
    type: "PARCEL_RELEASED",
    title: "Parcel Released: SPX-PH-2026-7734",
    description: "Verified passcode CK-7734 and handed package to Juan Dela Cruz (Self).",
    timestamp: "Sept 15, 2026 • 05:20 PM",
    actor: "Lobby Staff Admin",
    trackingNumber: "SPX-PH-2026-7734",
    badgeColor: "bg-green-600",
  },
];

export const SEED_SMS_LOGS: SmsLogItem[] = [
  {
    id: "sms-1",
    recipientPhone: "0917 123 4567",
    recipientName: "Juan Dela Cruz",
    messageText: "CK Condo Drop Hub: Package SPX-PH-2026-8921 from SPX Express has arrived at Shelf A-04. Your claim passcode is CK-8921. Free holding until Sept 21, 2026.",
    status: "DELIVERED",
    timestamp: "Sept 18, 2026 • 10:46 AM",
    trackingNumber: "SPX-PH-2026-8921",
    costEstimate: "₱0.40",
  },
  {
    id: "sms-2",
    recipientPhone: "0917 123 4567",
    recipientName: "Juan Dela Cruz",
    messageText: "CK Condo Drop Hub: Package JT-PH-9920148 from J&T Express has arrived at Shelf B-12. Your claim passcode is CK-0148. Free holding until Sept 22, 2026.",
    status: "DELIVERED",
    timestamp: "Sept 19, 2026 • 02:16 PM",
    trackingNumber: "JT-PH-9920148",
    costEstimate: "₱0.40",
  },
  {
    id: "sms-3",
    recipientPhone: "0918 234 5678",
    recipientName: "Maria Santos",
    messageText: "CK Condo Drop Hub: Package LBC-2026-33901 from LBC Express has arrived at Shelf B-02. Your claim passcode is CK-3901. Free holding until Sept 23, 2026.",
    status: "DELIVERED",
    timestamp: "Sept 20, 2026 • 09:16 AM",
    trackingNumber: "LBC-2026-33901",
    costEstimate: "₱0.40",
  },
];

export const DEFAULT_HUB_SETTINGS: HubSettings = {
  hubName: "CK Condo Drop Hub",
  buildingName: "CK Buildersville Condominium",
  stationName: "Lobby Counter",
  freeDaysRegular: 15,
  freeDaysPremium: 30,
  overdueFeePerDay: 10,
  smsSenderId: "CKCONDO",
  autoPrintIntakeLabel: true,
  soundEnabled: true,
  maxShelfSlots: 60,
};

export const SEED_INQUIRIES: DeskInquiry[] = [
  {
    id: "inq-101",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    residentUnit: "Unit 101, Tower A",
    residentPhone: "0917 123 4567",
    category: "Doorstep Delivery Request",
    trackingNumber: "SPX-PH-2026-8921",
    message: "Hi Lobby team, I have a package ready. Could Staff Admin bring it up to Unit 101 between 2:00 PM and 4:00 PM today? Thank you!",
    status: "RESOLVED",
    adminReply: "Package brought to Unit 101 by Staff Admin Carlos. Received by resident.",
    createdAt: "Sept 24, 2026 • 09:30 AM",
    updatedAt: "Sept 24, 2026 • 02:45 PM",
  },
  {
    id: "inq-102",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    residentUnit: "Unit 304, Tower B",
    residentPhone: "0918 234 5678",
    category: "Missing / Misplaced Package",
    trackingNumber: "JT-PH-9920148",
    message: "Shopee app says rider delivered package this morning, but I haven't received an SMS alert yet. Can you please check if it arrived?",
    status: "IN_PROGRESS",
    adminReply: "Checking shelf bin intake. Staff on duty is scanning morning drop batches.",
    createdAt: "Sept 25, 2026 • 10:15 AM",
    updatedAt: "Sept 25, 2026 • 10:45 AM",
  },
  {
    id: "inq-103",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    residentUnit: "Unit 101, Tower A",
    residentPhone: "0917 123 4567",
    category: "Authorized Proxy Claimant",
    message: "Authorizing my brother Ramon Dela Cruz to pick up parcels on my behalf this weekend with his valid Driver's License.",
    status: "RESOLVED",
    adminReply: "Noted with thanks. Ramon Dela Cruz added to verified proxy release logs.",
    createdAt: "Sept 24, 2026 • 03:00 PM",
    updatedAt: "Sept 24, 2026 • 03:20 PM",
  },
];
