import { Parcel, ResidentProfile, AuthUser } from "@/types";

export const SEED_USERS: AuthUser[] = [
  {
    id: "usr-resident-1",
    email: "juan.delacruz@example.com",
    name: "Juan Dela Cruz",
    phone: "0917 123 4567",
    role: "resident",
    unit: "Unit 101",
    tower: "Tower A",
    plan: "PREMIUM",
    residentCode: "CK-000123",
    createdAt: "2026-08-01T08:00:00Z",
  },
  {
    id: "usr-resident-2",
    email: "maria.santos@example.com",
    name: "Maria Santos",
    phone: "0918 234 5678",
    role: "resident",
    unit: "Unit 304",
    tower: "Tower B",
    plan: "REGULAR",
    residentCode: "CK-000189",
    createdAt: "2026-08-15T09:30:00Z",
  },
  {
    id: "usr-admin-1",
    email: "admin@ckcondohub.com",
    name: "Station 1 Front Desk Staff",
    phone: "0917 999 8888",
    role: "admin",
    createdAt: "2026-07-01T08:00:00Z",
  },
];

export const SEED_RESIDENTS: ResidentProfile[] = [
  {
    id: "usr-resident-1",
    name: "Juan Dela Cruz",
    email: "juan.delacruz@example.com",
    phone: "0917 123 4567",
    unit: "Unit 101",
    tower: "Tower A",
    building: "CK Buildersville Condominium",
    plan: "PREMIUM",
    residentCode: "CK-000123",
    authorizedClaimant: "Maria Dela Cruz (Spouse)",
    claimantPhone: "0918 987 6543",
    notifications: {
      smsArrival: true,
      smsReminder: true,
      emailDigest: false,
      promoUpdates: false,
    },
    deliveryCreditsLeft: 2,
    totalParcelsReceived: 18,
    activeParcelsCount: 3,
    status: "ACTIVE",
    createdAt: "2026-08-01T08:00:00Z",
  },
  {
    id: "usr-resident-2",
    name: "Maria Santos",
    email: "maria.santos@example.com",
    phone: "0918 234 5678",
    unit: "Unit 304",
    tower: "Tower B",
    building: "CK Buildersville Condominium",
    plan: "REGULAR",
    residentCode: "CK-000189",
    authorizedClaimant: "Carlo Santos (Son)",
    claimantPhone: "0919 111 2222",
    notifications: {
      smsArrival: true,
      smsReminder: true,
      emailDigest: true,
      promoUpdates: true,
    },
    deliveryCreditsLeft: 0,
    totalParcelsReceived: 9,
    activeParcelsCount: 1,
    status: "ACTIVE",
    createdAt: "2026-08-15T09:30:00Z",
  },
  {
    id: "usr-resident-3",
    name: "Robert Lim",
    email: "robert.lim@example.com",
    phone: "0920 345 6789",
    unit: "Unit 512",
    tower: "Tower A",
    building: "CK Buildersville Condominium",
    plan: "PER_PARCEL",
    residentCode: "CK-000215",
    notifications: {
      smsArrival: true,
      smsReminder: false,
      emailDigest: false,
      promoUpdates: false,
    },
    totalParcelsReceived: 4,
    activeParcelsCount: 1,
    status: "ACTIVE",
    createdAt: "2026-09-01T14:20:00Z",
  },
];

export const SEED_PARCELS: Parcel[] = [
  {
    id: "pcl-101",
    trackingNumber: "SPX-PH-2026-8921",
    courier: "SPX Express",
    courierColor: "#EE4D2D",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Shelf A-04",
    size: "Small",
    dateArrived: "Sept 18, 2026 • 10:45 AM",
    deadline: "Sept 21, 2026",
    holdingFee: "₱0.00 (Free)",
    status: "READY",
    claimCode: "CK-8921",
    notes: "Fragile sticker attached",
  },
  {
    id: "pcl-102",
    trackingNumber: "JT-PH-9920148",
    courier: "J&T Express",
    courierColor: "#D21F1F",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Shelf B-12",
    size: "Medium",
    dateArrived: "Sept 19, 2026 • 02:15 PM",
    deadline: "Sept 22, 2026",
    holdingFee: "₱0.00 (Free)",
    status: "READY",
    claimCode: "CK-0148",
  },
  {
    id: "pcl-103",
    trackingNumber: "FL-2026-58190",
    courier: "Flash Express",
    courierColor: "#FFB800",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Shelf C-01",
    size: "Large",
    dateArrived: "Sept 16, 2026 • 11:30 AM",
    deadline: "Sept 19, 2026 (Overdue)",
    holdingFee: "₱10.00 (1 Day)",
    status: "OVERDUE",
    claimCode: "CK-8190",
  },
  {
    id: "pcl-104",
    trackingNumber: "LBC-2026-33901",
    courier: "LBC Express",
    courierColor: "#E31837",
    residentId: "usr-resident-2",
    residentName: "Maria Santos",
    unit: "Unit 304 - Tower B",
    shelf: "Shelf B-02",
    size: "Small",
    dateArrived: "Sept 20, 2026 • 09:15 AM",
    deadline: "Sept 23, 2026",
    holdingFee: "₱0.00 (Free)",
    status: "READY",
    claimCode: "CK-3901",
  },
  {
    id: "pcl-105",
    trackingNumber: "SPX-PH-2026-7734",
    courier: "SPX Express",
    courierColor: "#EE4D2D",
    residentId: "usr-resident-1",
    residentName: "Juan Dela Cruz",
    unit: "Unit 101 - Tower A",
    shelf: "Archived",
    size: "Small",
    dateArrived: "Sept 13, 2026 • 09:00 AM",
    deadline: "Sept 16, 2026",
    holdingFee: "₱0.00",
    status: "PICKED_UP",
    claimCode: "CK-7734",
    claimedAt: "Sept 15, 2026 • 05:20 PM",
    claimedBy: "Juan Dela Cruz (Self)",
  },
];
